[firebase]
type = "service_account"
project_id = "southkorea-e794c"
private_key_id = "4332eb7082ad4f1e610e7938b2920a57d826544d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2PihBVgUsoZKv
C3wx0mvB95CtCe/jm+V+y/2+w2O/yw8shIDVIOfuW02+Rzc8/tHo6jXRproTTdLS
mqZLtzzJcDEPYZlPxwfwGvhYzB1HNTdlz7jleMSc4YutRj+0zhvPEqhQbm19FETp
DEdxmzxVeTbFWQaaSyKpyAgqSIQtIPq1IThWvUbUlE4yQ6ksIUPmVwPeokMHQMA5
VCcxv23hzqnNmNOqZ8wA5qckrRYZTwwLlaEsCA5eeNjLFWgy91fX/i+PgvivyE0z
8ykm9GLEKPPBGDKJytyFrgy+2p7cIYqVInDQ5TsuE5WrntyE6V2doGNNa6FW60q2
7Z6tVk5hAgMBAAECggEAEuXnLr9I0hP/Lf+25UO4wOh3LDp3kda8uaVVrs58LYtV
C3zCD1fWNTVqnmysIbsa8Vg4NIFhklbjocs/q2JY/1qO+9VXHJq7C/7/+dVQw+2U
zQ35UnJvkQUigtliCdHFuHdq1MxetjW/35rSXcmHPCXRtC1DLgTUl16S2i+i5Tr1
W8bHk2e5vrDSUVazFGzX6V+RfQrdRw0au7ud/OyswxQtczmbUQKO67qdRGWRupB6
siRraQIyKR7UQiKDoKpxWrzKiqE/Zdmw+5rhSgWriCy815g/Iig56tFrVAampm2f
FEpLx9EKsW908oq70Ppq4qVV/zDSVtiUPJp2QM4uQQKBgQDn1uDF0GHHqUKd4aA7
RmjzO23EC4EljfpeY1g3T9NiBkBviNpFwgmyPSkD+XdD6wrNYaarL5xOjBUF/Ckz
LbyvNZsLoDi1LhOcLldKIxiukS7WEQ39dRw1r06HMxLgkQ88DzTFDMA1kI4SNa6D
oNtH8LUikU6qvm/0fuvmw6l6fQKBgQDJPB5EowMoIzyOVNGr28c4LKnbc2+uWkvj
1qYjF50HMijNWgZ7bTGnUJDZTI28em0H3o2QrWfc7aAK0uLzDgqERth4L1XwqxnW
8ZLyka8yGHKegPzYUu+XM/ftAa+IwyaXYPX0nT0vtibMdrRJ/BREfvRE7xYgC1ab
LypxuZfEtQKBgBCSxty9SdApJG7+6yJxpR0GOZGTNPdHUAehWHQTy8utILwYb2of
New8/Qqgscr0KYCHI5AHRkhDMVmNLjDPazanQV8yY/tnwNUgZvMQ0TnhfRSmgXaG
Aa9Ayf9WQlo1ZH5po98WS0NJAy8AEWqtfB+HcJt5AcOo+33h+OE1SY9NAoGBAKkk
/RQYKNkd9RJ1vN9FlohjEkrBFshoYY2aqH6qpHSd9qnU18n7GFdYYsgjjqc0CF0q
9bb76mdK3ND8PYKq9LAGlIFA2G24g7mlyCxXw/jJj94m8WArJfPj3Kq8Vf0Qe2mW
OGZpnDp0UtxdkmD1n1uLkmo2xFQe86bw2C5LH4RZAoGBALd4yCQwB6HVZKN/8wEU
HZP2OebEunslC7UgBS4Srh2Q5CaojiyoCuYS988qVmzN4tpza1Qd4c0OCuefY/Rj
KnIekO3KGZp69Ke4wbi7tM0VMoZUNQWWWuVwxBn1SH02/rfNFK9O9MKWsfKY5yVx
XV3FD80cM9WEdNfCs4GsXGKN
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@southkorea-e794c.iam.gserviceaccount.com"
client_id = "117863158864625618479"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40southkorea-e794c.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
